name: TorchEnv
dependencies:
  - pandas
  - pandas-profiling
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - openpyxl
  - sweetviz
  - pip
  - pip:
    - pinecone-client
    - faiss-cpu
    - openai
    - streamlit-audiorecorder
    - ffmpeg-python
    - openai-whisper
    - librosa
    - streamlit-chat
    - boto3
    - langchain 
    - pymysql
    - chromadb
    - pexpect
    - audio-recorder-streamlit
    - streamlit-audiorecorder
    - flask
    - tiktoken
    - tabulate



 
