name: TorchEnv
dependencies:
  - pandas
  - pip
  - pip:
    - pinecone-client
    - faiss
    - openai
    - streamlit-audiorecorder
    - ffmpeg-python
    - openai-whisper
    - librosa
    - streamlit-chat
    - boto3
    - langchain 
    - pymysql
    - chromadb
    - pexpect
    - audio-recorder-streamlit
    - streamlit-audiorecorder
    - flask
    - streamlit_chat


 
