name: TorchEnv
dependencies:
  - numpy
  - pandas
  - pip
  - pip:
    - matplotlib
    - pinecone-client
    - openai
    - streamlit-audiorecorder
    - git+https://github.com/openai/whisper.git -q
