name: TorchEnv
dependencies:
  - pandas-profiling
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - openpyxl
  - pip
  - pip:
    - streamlit-pandas-profiling
    - pinecone-client
    - openai
    # - streamlit-audiorecorder
    # - ffmpeg-python
    # - openai-whisper
    # - librosa
    - streamlit-chat
    # - boto3
    - langchain 
    # - pymysql
    # - pexpect
    # - audio-recorder-streamlit
    # - streamlit-audiorecorder
    # - flask
    # - tiktoken
    # - tabulate
    # # - sweetviz
    # - loguru


 
